name: GitHub Actions containerization
on:
  push:
    branches:
      - main
      - nuxt-refactor
  workflow_dispatch:

jobs:

  build-container:
    name: Build container image
    runs-on: ubuntu-latest
    steps:

      - name: Set up Docker Buildx
        id: docker-setup
        uses: docker/setup-buildx-action@v4

      - name: Generate Docker Metadata
        id: docker-meta
        uses: docker/metadata-action@v6
        with:
          images: ${{ vars.IMAGE_NAME }}
          tags: |
            type=sha,format=long
            type=ref,event=branch
            type=ref,event=tag
            type=ref,event=pr

      - name: Build & Push docker image
        id: docker-build
        uses: docker/build-push-action@v7
        with:
          tags: ${{ steps.docker-meta.outputs.tags }}
          labels: ${{ steps.docker-meta.outputs.labels }}
          load: true

      - name: Export docker image to tar archive
        run: docker image save ${{ vars.IMAGE_NAME }} -o ${{ vars.IMAGE_NAME }}.tar

      - name: Upload docker image as artifact
        uses: actions/upload-artifact@v7
        with:
          path: ${{ vars.IMAGE_NAME }}.tar

  push-image:
    name: Push image to server
    runs-on: ubuntu-slim
    needs: build-container
    environment: wyrm.host
    steps:

      - name: Pull image artifact
        uses: actions/download-artifact@v8

      - name: Activate ssh private key
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.DEPLOY_SSH_KEY }}

      - name: List files
        run: ls -lah .

      - name: Push image to server
        run: cat ./${{ vars.IMAGE_NAME }}.tar | ssh -o "StrictHostKeyChecking=no" ${{ vars.DEPLOY_SERVER }} docker image load
