name: GitHub Actions containerization
on:
  push:
    branches:
      - main
      - nuxt-refactor
  workflow_dispatch:

jobs:

  build-container:
    name: Build container image
    uses: docker/github-builder/.github/workflows/build.yml@v1
    permissions:
      contents: read # to fetch the repository content
    with:
      output: local
      cache: true
      meta-images: ${{ vars.IMAGE_NAME }}
      artifact-name: ${{ vars.IMAGE_NAME }}
      artifact-upload: true

  push-image:
    name: Push image to server
    runs-on: ubuntu-slim
    needs: build-container
    environment: wyrm.host
    steps:
      - name: Pull image artifact
        uses: actions/download-artifact@v5
        with:
          name: ${{ vars.IMAGE_NAME }}

      - name: Activate ssh private key
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Push image to server
        run: cat ${{ vars.IMAGE_NAME }}.tar | ssh -o "StrictHostKeyChecking=no" ${{ vars.REMOTE_SERVER }} docker image load
